export enum ResponseMessage {
    ACCOUNT_DELETED = "That your account has been deleted, we apologize. Please let us know if you need any help or if you have any questions.",
    ACCOUNT_DELETED_PERMANENT = "All associated data was successfully deleted and the account was successfully cleared.",
    ACCOUNT_RESTORED = "Good news! Your account has been restored successfully. Hello again! Please feel free to ask any questions or for additional help.",
    ACCOUNT_NOT_FOUND = "We apologize, but the requested account was not found.",
    EMPTY_TOKEN = "The supplied token is not valid. Make sure token field is entered correctly.",
    EMPTY_PASSWORD = "To ensure the security of your account, kindly provide a password.",
    EMPTY_EMAIL = "Please enter a working email address. Email is a necessary field.",
    INVALID_EMAIL = "Please enter a correct email address.",
    CHECK_EMAIL = "Please check your email for any additional instructions",
    WEAK_PASSWORD = "Please pick a password that is at least 8 characters long for the security of your account.",
    UNVERIFIED_ACCOUNT = "Please be aware that your account has not yet been verified, which we regret. A critical step in ensuring the safety and reliability of our platform is account verification. Please check your registered email for a verification link or further instructions before continuing. Please double-check your spam or junk folder if you haven't received a verification email. ",
    WRONG_PASSWORD = "Sorry, but the password you provided is unreliable. Please try again after double-checking your password.",
    EMPTY_ACCESS_CODE = "Please enter the needed access code to continue.",
    WRONG_ACCESS_CODE = "Denied access. The access code you entered is inapplicable. Please check the code and try once more.",
    INVALID_ACCOUNT_ID = "We apologize for the inconvenience, but the provided Account ID appears to be invalid. Please double-check the ID and ensure its accuracy.",
    ACCOUNT_UPDATED = "Congratulations on finishing up your account update! Your suggestions have been carried out.",
    WORK_NOT_FOUND = "We're sorry to let you know that we were unable to locate the requested work. Please double-check your entry of accurate information before attempting again.",
    RESUME_NOT_FOUND = "We regret the inconvenience, but we were unable to locate the requested resume. Please verify the information provided.",
    RESUME_CREATED = "Congratulations on creating a successful resume! This crucial document will aid in showcasing your abilities, credentials, and experiences. ",
    RESUME_CONFLICT = "We've noted that your resume is already on file. We are unable to produce new resumes for you repeatedly in accordance with our policy.",
    RESUME_UPDATED = "You've done a great job updating your resume! You can make sure your resume accurately represents your skills and experiences by keeping it up-to-date and pertinent.",
    RESUME_DELETED = "The deletion of your resume was successful. In order to protect the privacy and confidentiality of your information, it has been removed from our system.",
    WORK_UPDATED = "Congratulations on finishing your work update! Your dedication to honing and enhancing your work is admirable. ",
    WORK_DELETED = "Your writing has been effectively erased. All related information has been permanently deleted, and it has been taken out of our records.",
    WORK_CREATED = "Congratulations on completing your work successfully! This is a noteworthy accomplishment that highlights your talent and commitment.",
}